"""
A simple program for modelling a number guessing game.

EXAMPLE:

Welcome to the Number Guessing Game!
What is your name? Ave

Welcome, Ave!
Let's start the game, shall we?

Ave, please select a number between 1 and 10: 5
Try again!

Ave, please select a number between 1 and 10: 3
You got it! It took you 1 tries!

Ave, do you wish to play again? [Y]es: n

Ave, thanks for playing!
Stay safe!

"""

import random
import sys


class NumberGuessingGame:
    """
    Model a number guessing game.
    """

    def __init__(self):
        """Initializing variables."""
        self.number_of_tries = 0
        self.user_name = input("\nWelcome to the Number Guessing Game!\n"
                               "What is your name? ").capitalize()

    def welcome_the_user(self):
        """Welcome the user."""
        welcome_message = f"\nWelcome, " \
                          f"{self.user_name}!\nLet's start the game, shall we?"
        return welcome_message

    def validate_user_input(self):
        """
        Make sure the user input is a number between 1-10 and return it.
        """
        while True:
            try:
                selection = int(input(
                    f"\n{self.user_name},"
                    f" please select a number between 1 and 10: "))
                if not 1 <= selection <= 10:
                    raise ValueError
                return selection
            except ValueError:
                print("Sorry, your input is not valid.")

    def get_number(self):
        """Get the validated number from function validate_user_input()."""
        number = self.validate_user_input()
        return number

    def play_the_game(self):
        """
        Check if the number guessed by the user matches
        the number generated by random-function.
        If not, ask the user to try again, else congratulate
        the user and let him/her know how many tries it took
        him/her to guess the number.
        """
        winning_number = random.randint(1, 10)
        while self.get_number() != winning_number:
            print("Try again!")
            self.number_of_tries += 1
        print(f"You got it! It took you {self.number_of_tries} tries!")
        self.number_of_tries = 0
        self.play_again()

    def play_again(self):
        """
        Ask the user if he/she wants to play again.
        Based on the answer either restart the game
        or exit the program with exit code 0 (clean exit).
        """
        user_ip = input(f"\n{self.user_name}, "
                        f"do you wish to play again? [Y]es: ")
        if user_ip.lower() == 'y':
            self.play_the_game()
        print(f"\n{self.user_name}, thanks for playing!\n"
              f"Stay safe!")
        sys.exit(0)


INST = NumberGuessingGame()
print(INST.welcome_the_user())
print(INST.play_the_game())
